sudo: false

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - vim-gtk
      - silversearcher-ag

before_script:
  - if [[ "$TRAVIS_OS_NAME" == osx ]]; then brew update && brew install vim; fi

script:
  - test/run
